name: covid19-infobot
channels:
  - defaults
  - anaconda
dependencies:
  - python=3.8.1
  - beautifulsoup4=4.8.2
  - pip:
    - python-telegram-bot==12.4.2
    - googletrans==2.4.0
    - lxml==4.5.0
    - gspread==3.3.0
    - oauth2client==4.1.3
